/* Auth */
export const BEGIN_LOAD_USER = 'BEGIN_LOAD_USER';
export const SUCCESS_LOAD_USER = 'SUCCESS_LOAD_USER';
export const FAIL_LOAD_USER = 'FAIL_LOAD_USER';
export const SUCCESS_SIGNUP = 'SUCCESS_SIGNUP';
export const FAIL_SIGNUP = 'FAIL_SIGNUP';
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN';
export const FAIL_LOGIN = 'FAIL_LOGIN';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

/* Portfolio */
export const CHOOSE_DEFAULT_PORTFOLIO = 'CHOOSE_DEFAULT_PORTFOLIO';
export const GET_DEFAULT_PORTFOLIO = 'GET_DEFAULT_PORTFOLIO';
export const LOAD_PORTFOLIO = 'LOAD_PORTFOLIO';
export const CREATE_PORTFOLIO = 'CREATE_PORTFOLIO';
export const EDIT_PORTFOLIO = 'EDIT_PORTFOLIO';
export const DELETE_PORTFOLIO = 'DELETE_PORTFOLIO';
export const PORTFOLIO_LOAD_ERROR = 'PORTFOLIO_LOAD_ERROR';
export const PORTFOLIO_CREATE_ERROR = 'PORTFOLIO_CREATE_ERROR';
export const PORTFOLIO_EDIT_ERROR = 'PORTFOLIO_EDIT_ERROR';
export const PORTFOLIO_DELETE_ERROR = 'PORTFOLIO_DELETE_ERROR';
export const EMPTY_PORTFOLIO = 'EMPTY_PORTFOLIO';

/* USER */
export const UPLOAD_AVATAR = 'UPLOAD_AVATAR';
export const AVATAR_ERROR = 'AVATAR_ERROR';
export const UPDATE_USER = 'UPDATE_USER';
export const FAIL_UPDATE_USER = 'FAIL_UPDATE_USER';

/* ALERT */
export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';

/* STOCK */
export const RESET_STOCK_LOADING = 'RESET_STOCK_LOADING';
export const RESET_REALIZE_STOCK_LOADING = 'RESET_REALIZE_STOCK_LOADING';
export const GET_STOCK_LIST = 'GET_STOCK_LIST';
export const GET_EMPTY_STOCK_LIST = 'GET_EMPTY_STOCK_LIST';
export const GET_STOCK_ERROR = 'GET_STOCK_ERROR';
export const GET_STOCK_GROUP = 'GET_STOCK_GROUP';
export const GET_STOCK_GROUP_ERROR = 'GET_STOCK_GROUP_ERROR';
export const GET_REALIZED_STOCKS = 'GET_REALIZED_STOCKS';
export const GET_REALIZED_STOCKS_ERROR = 'GET_REALIZED_STOCKS_ERROR';
export const ADD_STOCK = 'ADD_STOCK';
export const EDIT_STOCK = 'EDIT_STOCK';
export const DELETE_STOCK = 'DELETE_STOCK';
export const CHECK_MARKET_STATUS = 'CHECK_MARKET_STATUS';
export const CHECK_MARKET_STATUS_ERROR = 'CHECK_MARKET_STATUS_ERROR';
export const EDIT_DAILY_RETURN = 'EDIT_DAILY_RETURN';
export const EDIT_OVERALL_RETURN = 'EDIT_OVERALL_RETURN';
export const GET_SECTOR = 'GET_SECTOR';
export const GET_SECTOR_ERROR = 'GET_SECTOR_ERROR';
export const CLOSE_POSITION = 'CLOSE_POSITION';
export const CLOSE_POSITION_ERROR = 'CLOSE_POSITION_ERROR';

/* CASH */
export const GET_CASH_LIST = 'GET_CASH_LIST';
export const GET_TOTAL_CASH = 'GET_TOTAL_CASH';
export const GET_CASH_ERROR = 'GET_CASH_ERROR';
export const ADD_CASH = 'ADD_CASH';
export const ADD_CASH_ERROR = 'ADD_CASH_ERROR';
export const EDIT_CASH = 'EDIT_CASH';
export const EDIT_CASH_ERROR = 'EDIT_CASH_ERROR';
export const DELETE_CASH = 'DELETE_CASH';
export const DELETE_CASH_ERROR = 'DELETE_CASH_ERROR';


