/* Auth */
export const BEGIN_LOAD_USER = 'BEGIN_LOAD_USER';
export const SUCCESS_LOAD_USER = 'SUCCESS_LOAD_USER';
export const FAIL_LOAD_USER = 'FAIL_LOAD_USER';
export const SUCCESS_SIGNUP = 'SUCCESS_SIGNUP';
export const FAIL_SIGNUP = 'FAIL_SIGNUP';
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN';
export const FAIL_LOGIN = 'FAIL_LOGIN';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

/* Portfolio */
export const CHOOSE_DEFAULT_PORTFOLIO = 'CHOOSE_DEFAULT_PORTFOLIO';
export const START_LOAD_DEFAULT_PORTFOLIO = 'START_LOAD_DEFAULT_PORTFOLIO';
export const SUCCESS_LOAD_DEFAULT_PORTFOLIO = 'SUCCESS_LOAD_DEFAULT_PORTFOLIO';
export const FAIL_LOAD_DEFAULT_PORTFOLIO = 'FAIL_LOAD_DEFAULT_PORTFOLIO';
export const SUCCESS_GET_DEFAULT_PORTFOLIO_NAME = 'SUCCESS_GET_DEFAULT_PORTFOLIO_NAME';
export const FAIL_GET_DEFAULT_PORTFOLIO_NAME = 'FAIL_GET_DEFAULT_PORTFOLIO_NAME';
export const START_LOAD_PORTFOLIO_LIST = 'START_LOAD_PORTFOLIO_LIST';
export const SUCCESS_LOAD_PORTFOLIO_LIST = 'SUCCESS_LOAD_PORTFOLIO_LIST';
export const FAIL_LOAD_PORTFOLIO_LIST = 'FAIL_LOAD_PORTFOLIO_LIST';
export const CREATE_PORTFOLIO = 'CREATE_PORTFOLIO';
export const EDIT_PORTFOLIO = 'EDIT_PORTFOLIO';
export const DELETE_PORTFOLIO = 'DELETE_PORTFOLIO';
export const PORTFOLIO_CREATE_ERROR = 'PORTFOLIO_CREATE_ERROR';
export const PORTFOLIO_EDIT_ERROR = 'PORTFOLIO_EDIT_ERROR';
export const PORTFOLIO_DELETE_ERROR = 'PORTFOLIO_DELETE_ERROR';
export const EMPTY_PORTFOLIO_LIST = 'EMPTY_PORTFOLIO_LIST';

/* USER */
export const UPLOAD_AVATAR = 'UPLOAD_AVATAR';
export const FAIL_UPLOAD_AVATAR = 'FAIL_UPLOAD_AVATAR';
export const UPDATE_USER = 'UPDATE_USER';
export const FAIL_UPDATE_USER = 'FAIL_UPDATE_USER';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const FAIL_UPDATE_PASSWORD = 'FAIL_UPDATE_PASSWORD';
export const DELETE_AVATAR = 'DELETE_AVATAR';
export const FAIL_DELETE_AVATAR = 'FAIL_DELETE_AVATAR';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const FAIL_DELETE_ACCOUNT = 'FAIL_DELETE_ACCOUNT';

/* ALERT */
export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';

/* STOCK */
export const START_GET_STOCK_LIST = 'START_GET_STOCK_LIST';
export const SUCCESS_GET_STOCK_LIST = 'SUCCESS_GET_STOCK_LIST';
export const FAIL_GET_STOCK_LIST = 'FAIL_GET_STOCK_LIST';
export const GET_EMPTY_STOCK_LIST = 'GET_EMPTY_STOCK_LIST';
export const GET_STOCK_ERROR = 'GET_STOCK_ERROR';
export const START_GET_STOCK_GROUP = 'START_GET_STOCK_GROUP';
export const SUCCESS_GET_STOCK_GROUP = 'SUCCESS_GET_STOCK_GROUP';
export const FAIL_GET_STOCK_GROUP = 'FAIL_GET_STOCK_GROUP';
export const START_GET_REALIZED_STOCKS = 'START_GET_REALIZED_STOCKS';
export const SUCCESS_GET_REALIZED_STOCKS = 'SUCCESS_GET_REALIZED_STOCKS';
export const FAIL_GET_REALIZED_STOCKS = 'FAIL_GET_REALIZED_STOCKS';
export const SUCCESS_ADD_STOCK = 'SUCCESS_ADD_STOCK';
export const FAIL_ADD_STOCK = 'FAIL_ADD_STOCK';
export const SUCCESS_EDIT_STOCK = 'SUCCESS_EDIT_STOCK';
export const FAIL_EDIT_STOCK = 'FAIL_EDIT_STOCK';
export const DELETE_STOCK = 'DELETE_STOCK';
export const CHECK_MARKET_STATUS = 'CHECK_MARKET_STATUS';
export const CHECK_MARKET_STATUS_ERROR = 'CHECK_MARKET_STATUS_ERROR';
export const SUCCESS_CALCULATE_RETURN = 'SUCCESS_CALCULATE_RETURN';
export const FAIL_CALCULATE_RETURN = 'FAIL_CALCULATE_RETURN';
export const DELETE_QUOTE = 'DELETE_QUOTE';
export const DELETE_QUOTE_ERROR = 'DELETE_QUOTE_ERROR';
export const UPDATE_PROGRESS = 'UPDATE_PROGRESS';
export const DONE_PROGRESS = 'DONE_PROGRESS';
export const FAIL_PROGRESS = 'FAIL_PROGRESS';
export const GET_REALTIME_PRICE = 'GET_REALTIME_PRICE';
export const DISCONNECT_SSE = 'DISCONNECT_SSE';

/* CASH */
export const START_GET_CASH_LIST = 'START_GET_CASH_LIST';
export const SUCCESS_GET_CASH_LIST = 'SUCCESS_GET_CASH_LIST';
export const FAIL_GET_CASH_LIST = 'FAIL_GET_CASH_LIST';
export const START_GET_TOTAL_CASH = 'START_GET_TOTAL_CASH';
export const SUCCESS_GET_TOTAL_CASH = 'SUCCESS_GET_TOTAL_CASH';
export const FAIL_GET_TOTAL_CASH = 'FAIL_GET_TOTAL_CASH';
export const ADD_CASH = 'ADD_CASH';
export const ADD_CASH_ERROR = 'ADD_CASH_ERROR';
export const EDIT_CASH = 'EDIT_CASH';
export const EDIT_CASH_ERROR = 'EDIT_CASH_ERROR';
export const DELETE_CASH = 'DELETE_CASH';
export const DELETE_CASH_ERROR = 'DELETE_CASH_ERROR';